# Generated by Django 5.2.1 on 2025-06-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_is_admin_userprofile_is_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('owner', 'Owner')], default='employee', max_length=10),
        ),
    ]
